name       : stubby
version    : 0.2.3
release    : 1
source     :
    - https://github.com/getdnsapi/stubby/archive/v0.2.3.tar.gz : 5fbe10f421f1313b5e2259b0eec96785af0c5b460431cf86bb6450a11cb3f473
license    : BSD-3-Clause
component  : network.util
summary    : Stubby is the name given to a mode of using getdns which enables it to act as a local DNS Privacy stub resolver (using DNS-over-TLS)
description: |
    Stubby is an application that acts as a local DNS Privacy stub resolver (using DNS-over-TLS). Stubby encrypts DNS queries sent from a client machine (desktop or laptop) to a DNS Privacy resolver increasing end user privacy.
builddeps  :
    - pkgconfig(getdns)
    - pkgconfig(yaml-0.1)
setup      : |
    %patch -p1 < $pkgfiles/0001-Support-a-stateless-configuration.patch
    %patch -p1 < $pkgfiles/0002-Cleanup-Makefile.patch

    %reconfigure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 systemd/stubby.conf -t $installdir/%libdir%/systemd/tmpfiles.d/
    install -Dm00644 systemd/stubby.service -t $installdir/%libdir%/systemd/system/

    install -Dm00644 $pkgfiles/stubby.sysusers $installdir/%libdir%/systemd/system/stubby.conf
